### ISSUE TITLE
ModuleNotFoundError: No module named 'toml'

### ISSUE THREAD

**Issue by aubricus** [aubricus/klak#225]
* Klak version: 0.4.1
* Python version: 3.7.3
* Operating System: OSX 10.14.5

### Description

Installed Klak and ran `klak` and received the error.

### What I Did

Here's the traceback.

```
Traceback (most recent call last):
  File "/Users/aubreytaylor/Repos/cookiecutter/cookiecutter-djangocms/.venv/bin/klak", line 6, in <module>
    from klak.cli import main
  File "/Users/aubreytaylor/Repos/cookiecutter/cookiecutter-djangocms/.venv/lib/python3.7/site-packages/klak/cli.py", line 6, in <module>
    from .klak import import_clickfile, get_version
  File "/Users/aubreytaylor/Repos/cookiecutter/cookiecutter-djangocms/.venv/lib/python3.7/site-packages/klak/klak.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

```

Note: Installing `toml` locally fixed the issue; but should be installed when klak is installed.

**Comment by aubricus** [comment]
Fixed in [4ebb210](https://github.com/aubricus/klak/commit/4ebb21097eacdb895001d99d5f9c165efe8ad448)
